server = "http://localhost:8033"
level = "trace"
show-qrcode = false
show-progress = true

[qrcode]
# black / red / green / yellow / blue / magenta / cyan / white
foreground = "black"
background = "white"

# Error Recovery
#  7% /   15%  / 25%  /  30%
# low / medium / high / highest
level = "low"

# left / center / right
align = "left"

# IceServers
# https://developer.mozilla.org/en-US/docs/Web/API/RTCConfiguration/iceServers#examples
[[iceservers]]
urls = [ "stun:stun.22333.fun", "stun:stun.example.com" ]

[[iceservers]]
urls = [ "stun:stun.services.mozilla.com" ]
username = "louis@mozilla.com"
credential = "webrtcdemo"

