server = "http://localhost:8033"
level = "trace"
qrcode = false
progress = true

[qrcode_config]
# black / red / green / yellow / blue / magenta / cyan / white
foreground = "black"
background = "white"

# Error Recovery
#  7% /   15%  / 25%  /  30%
# low / medium / high / highest
level = "low"

# left / center / right
align = "left"

